# Generated by Django 4.1.4 on 2022-12-13 13:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, verbose_name='Ответ')),
                ('asked_at', models.DateTimeField(auto_now_add=True, verbose_name='Вопрос задан')),
                ('answered_at', models.DateTimeField(blank=True, verbose_name='Ответили')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='customers.customer', verbose_name='Клиент')),
                ('who_answered', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='answered_questions', to='salons.staff', verbose_name='Кто ответил')),
            ],
        ),
    ]
