# Generated by Django 4.1.4 on 2022-12-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_staff_is_administrator'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв')),
                ('leaved_at', models.DateTimeField(auto_now_add=True, verbose_name='Отзыв оставлен')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='customers.customer', verbose_name='Клиент')),
                ('salon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='salons.salon', verbose_name='Салон')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks', to='salons.staff', verbose_name='Мастер')),
            ],
        ),
    ]
