# Generated by Django 4.1.4 on 2022-12-13 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='score',
            field=models.SmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
