# Generated by Django 4.1.4 on 2022-12-13 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_feedback_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('asked_at', models.DateTimeField(auto_now_add=True, verbose_name='Вопрос задан')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='customers.customer', verbose_name='Клиент')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
