# Generated by Django 4.1.4 on 2022-12-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_request_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фамилия'),
        ),
    ]
