# Generated by Django 4.1.4 on 2022-12-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_alter_masterschedule_finish_at_and_more'),
        ('customers', '0006_alter_customer_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Время записи')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Клиент')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='salons.master', verbose_name='Мастер')),
                ('procedure', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='salons.procedure', verbose_name='Салон')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='salons.salon', verbose_name='Салон')),
            ],
        ),
    ]
