# Generated by Django 4.1.4 on 2022-12-19 07:58

from django.db import migrations, models
from datetime import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.now(), verbose_name='created at'),
            preserve_default=False,
        ),
    ]
