# Generated by Django 4.1.4 on 2022-12-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0007_alter_masterschedule_finish_at_and_more'),
        ('customers', '0009_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='procedure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='salons.procedure', verbose_name='Процедура'),
        ),
    ]
