# Generated by Django 4.1.4 on 2022-12-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_staff_is_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта'),
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media/icons', verbose_name='Иконка')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_networks', to='salons.salon', verbose_name='Salon')),
            ],
        ),
    ]
