# Generated by Django 4.1.4 on 2022-12-15 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_rename_schedule_salonschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
            ],
        ),
        migrations.CreateModel(
            name='MasterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=30, verbose_name='День недели')),
                ('start_at', models.TimeField(verbose_name='Начинает работу в')),
                ('finish_at', models.TimeField(verbose_name='Заканчивает работу в')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='salons.master', verbose_name='Master')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_schedule', to='salons.salon', verbose_name='Salon')),
            ],
        ),
        migrations.AddField(
            model_name='procedure',
            name='specialization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='salons.specialization', verbose_name='Специализация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='salons.specialization', verbose_name='Специализация'),
        ),
    ]
