# Generated by Django 4.1.4 on 2022-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_specialization_masterschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterschedule',
            name='week_day',
            field=models.CharField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], max_length=30, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='salonschedule',
            name='week_day',
            field=models.CharField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], max_length=30, verbose_name='День недели'),
        ),
    ]
