# Generated by Django 4.1.4 on 2022-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_alter_masterschedule_week_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterschedule',
            name='finish_at',
            field=models.TimeField(null=True, verbose_name='Заканчивает работу в'),
        ),
        migrations.AlterField(
            model_name='masterschedule',
            name='start_at',
            field=models.TimeField(null=True, verbose_name='Начинает работу в'),
        ),
    ]
